### ISSUE TITLE
Maintenance of deps

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#116]
## Description

Update deps for `rpc-reflector`, `@mapeo/sqlite-indexer` and `multi-core-indexer`, fix typescript declarations, and ensure type declarations are included in npm package.

## Tasks

- [x] https://github.com/digidem/mapeo-sqlite-indexer/pull/6
- [x] https://github.com/digidem/rpc-reflector/pull/14
- [x] Fixes to `rpc-reflector` https://github.com/digidem/rpc-reflector/commits/main
- [x] https://github.com/digidem/multi-core-indexer/pull/6
- [x] https://github.com/digidem/multi-core-indexer/pull/7
- [x] https://github.com/digidem/multi-core-indexer/pull/8
