### ISSUE TITLE
Add `$sync` namespace methods to project instance API

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#134]
## Description

Add these methods to the API, managing the discovery and connection modules.

### Tasks

- [x] `project.$sync.getState()`
- [ ] `project.$sync.setDiscovery()`
- [x] `project.$sync.setSync()`
- [x] `project.$sync.stop()`
- Events
    - [x] `sync-state`

### Dependencies

- [x] #331
- [x] #351
