### ISSUE TITLE
Research and scope out indexing data

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#15]
## Description
Figure out what's needed for indexing data.

## Tasks
- [ ] Minimal prototyping of indexing approaches
- [ ] Write up trade-offs of indexing approaches
- [ ] Create issues for implementation
