### ISSUE TITLE
Cleanup protobuf code and add project keys encoding

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#200]
## Description

Currently the generated code sits alongside source code - it's not clear that it is generated.

## Tasks

- [ ] move generated messages files into `src/generated` #201
- [ ] add config namespace to RPC message #202
- [ ] update project info shared in invite #202
- [ ] add message encoding for project keys #203
