### ISSUE TITLE
Implement `close` method for MapeoProject class

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#207]
## Description

In order to avoid memory leaks and issues with redundant/dangling file connections, we should implement a `close` method on the MapeoProject class that handles the following:

## Tasks

- [ ] close the SQLite connection
- [ ] close any hypercore-related file connections
- [ ] close any discovery connections that it manages (currently doesn't do this but I think it will at some point)
