### ISSUE TITLE
Fix storage options for MapeoManager and MapeoProject

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#226]
## Description

Currently there are a few issues with how we define storage paths:

- Because we pass a storagePath instead of a storage function, there is no way in tests to set up re-usable memory storage.
- Currently project storage is not namespaced, so the project database will be overwritten by each project
- The filepool is set-up for each project instance. There should be one file pool for all storage across all projects

Switching to accepting a storage path or a storage function (similar to what Hypercore does) would allow us to pass `() => new RAM()` as storage, and persist RAM storage where needed for tests. It would also remove all the boilerplate in the code for setting up memory storage if storagePath is undefined

We want storage for each project to be stored in a separate folder. The folder name should be the projectPublicId. This means we will need to wrap the storage function that is passed to MapeoProject to append the projectId to the name - see [how corestore does this.](https://github.com/holepunchto/corestore/blob/a68c20c8aed0660540c5824e7f8930f4a8844af5/index.js#L251)

We would still need a path/folder for sqlite database files. It probably makes sense to pass a `dbPath` to MapeoProject and `dbFolder` to MapeoClient. `client.db`. We could store all databases in the same folder, if we name the project database files with the projectPublicId. This is probably be easier than trying to place the db file in folders alongside the hypercore storage / random-access-storage.

## Tasks

- [ ] Add `dbFolder` required option to MapeoManager
- [ ] Make `opts.storage` a required option, and allow a storage creation function (`name => new RandomAccessStorage(name)`)
- [ ] If a path is passed, use a [default random-access-file storage function](https://github.com/digidem/mapeo-core-next/blob/main/src/mapeo-project.js#L74-L78)
- [ ] Wrap the storage function passed to MapeoProject so that cores for each project are stored in separate folders named with the project public ID.
- [ ] Inside MapeoProject, the storage function will still need to be wrapped to separate index storage from core storage.
- [ ] Create a single instance of RandomAccessFilePool in MapeoManager and use that for all storages
- [ ] Remove boilerplate for handling undefined opts.storage and setting up memory storage in the module code
- [ ] Update tests to setup their own memory storage
- [ ] Add a `dbPath` required option to MapeoProject
- [ ] If `dbFolder` is `:memory:`, then pass `:memory:` as opts.dbPath to MapeoProject
- [ ] Otherwise `clientDbPath = path.join(opts.dbFolder, 'client.db')` and `new MapeoProject({ dbPath: path.join(dbFolder, projectId) })`
