### ISSUE TITLE
Add project.close()

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#227]
## Description

`project.close()` should close all storage and remove event listeners so that everything can be garbage collected, and another project instance can be created without trying to access / write to the same resources.

## Tasks

- [x] close multi-core-indexers
- [x] remove listeners on multi-core-indexers (in DataType)
- [x] close indexer storage
- [x] close hypercores
- [x] close hypercore storage
- [x] close project database
- [ ] figure out if anything else needs to be closed
