### ISSUE TITLE
Wrapping up MDNS Discovery

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#244]
## Description

MDNS discovery has proven challenging due to bugs in the module we have been using, and complexities of DNS-SD itself. A full write-up of outstanding issues is in https://github.com/digidem/mapeo-core-next/pull/177#issuecomment-1703299791

This issue is to track remaining work to merge https://github.com/digidem/mapeo-core-next/pull/177.

## Tasks

- [x] Create a separate abstraction for MDNS discovery and browsing, that can be unit tested separately. We can test this for ensuring that only one event is emitted for each discovered service, and we correctly handle services being gracefully closed down. This will allow us to swap out the MDNS module that we use while keeping the same API and tests.
- [x] Write unit tests for MDNS discovery and browsing with multiple clients (testing MDNS is always going to be limited since we're running all tests on the same machine. Ideally at some point we can set up a virtual network with docker machines or something similar)
- [ ] Thoroughly test de-duplication of connections and closing connections and servers, debug as necessary
- [ ] Add method to expose active connections - this will be used by project instances that get passed the discovery instance.
- [x] Use random ids as the instance name for service broadcast (can use this rather than the current txt method for de-duping)
