### ISSUE TITLE
Initial deviceInfo implementation

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#249]
## Description

This is a subtask of [Add device info records #182](https://github.com/digidem/mapeo-core-next/issues/182). 

As per https://github.com/digidem/mapeo-core-next/issues/240, we want a user to be able to set a device name at a device level (e.g. for all projects), but the data also needs to be stored in each individual project (so that other clients can read it).

We initially only want a device to only be able to write its own device name/info, and for that information to be shared across all projects. In the future we might want to allow administrators to name devices, and for a device to have different names on different projects.

## Tasks for initial implementation

- [x] Add a deviceInfo internal dataType
- [x] Add `client.setDeviceInfo()` and `client.getDeviceInfo()` methods
- [x] Create a client SQLite table for persisting local device info.

## Tasks for full implementation (tied to project.$member work)

- [ ] Implement `project.$member.update()` but only allow a device to update it's own deviceInfo (the role that is set by this method has different permissions, so needs to be evaluated separately)
- [ ] From MapeoManager, call `project.$member.update()` with the current device name when joining a project
- [ ] From the `client.setDeviceInfo()` method, call `project.$member.update()` for all current projects on the device
