### ISSUE TITLE
Change version IDs to use the discovery keys instead of core keys

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#265]
## Description

Core keys should be considered "sensitive" data. They are the authentication mechanism to replicate a hypercore. We have additional layers of security with the project key, encryption of hypercores, and the capabilities check before any cores are replicated, but it seems like we should still treat hypercore keys carefully.

Currently we use the hypercore key as part of the version ID. The risk is that we export data including the version ID without realizing its sensitive nature.

## Tasks

- [x] https://github.com/digidem/mapeo-schema/issues/141
- [ ] Lookup previous versions by discoveryKey in DataType
- [ ] Use the discovery key when decoding in the Indexer
