### ISSUE TITLE
Add fields to invites

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#275]
## Description

As part of the invite that's sent to a peer, we need to include a `role` field that identifies the role associated with the invite. This way the frontend can inform the user about the role they're being invited to join as

Also should ensure that the project has a name before allowing to invite peers

## Tasks

- [x] Add role name field
- [x] Add role description field
- [x] Invitor name
- [x] Assert the project has a name before allowing invite

**Comment by tomasciccola** [comment]
I'm starting to work on this issue and I'm wondering where this should live. 
From the context I would say we should start with modify the protobuf `Invite` schema to include the fields we are proposing. The Role protobuf schema lives on `mapeo-schema` so -maybe?- we should import the `Role` type on `proto/rpc.proto` and include the whole Role - or a subset, if it makes more sense?
@achou11 @gmaclennan wdyt??
