### ISSUE TITLE
Tracking Issue: Icons

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#293]
- [x]  https://github.com/digidem/mapeo-schema/issues/149
- [x]  https://github.com/digidem/mapeo-core-next/issues/292
-  ~https://github.com/digidem/mapeo-core-next/issues/291~ (redundant with IconApi)
- [x] https://github.com/digidem/mapeo-core-next/issues/296
- [x] https://github.com/digidem/mapeo-core-next/issues/333
