### ISSUE TITLE
Set up http server for blobs and icons in MapeoManager

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#329]
## Description

The plan is to set up a single server to handle http requests for both blobs (e.g. media) and icons (part of project configs). 

The implementation will roughly look similar to this:

```ts
this.#fastifyServer = new Fastify({...})

// Register the blob routes
this.#fastifyServer.register(BlobServerPlugin, {
  prefix: '/blob/',
  // whatever other opts...
)

// Register the icon routes
this.#fastifyServer.register(IconServerPlugin, {
  prefix: '/icon/',
  // whatever other opts...
)
```

## Tasks

- [ ] Create fastify server in `MapeoManager` and register the blob and icon plugins
- [x] Remove blob server creation in `MapeoProject`
- [x] Move blobServer to `MapeoManager` as a Plugin
- [x] Move iconServer to `MapeoManager` as a Plugin (#315 )

**Comment by achou11** [comment]
For that first task, wondering if there are any thoughts on making the server instance and contructor option for the MapeoManager?
