### ISSUE TITLE
add DataStore `.writeRaw` and `readRaw` methods

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#332]
## Description
In order to write and read an arbritrary Buffer to the `DataStore` we need a `writeRaw` and `readRaw` methods

## Tasks

- [x] Create `writeRaw` implementation
- [x] Create `readRaw` implementation
- [x] Write unit tests

rough implementation
```js

  /** @param {string} versionId */
  async readRaw(versionId) {
    const { coreDiscoveryKey, index } = parseVersionId(versionId)
    const core = this.#coreManager.getCoreByDiscoveryKey(coreDiscoveryKey)
    if (!core) throw new Error('Invalid versionId')
    const block = await core.get(index, { wait: false })
    if (!block) throw new Error('Not Found')
    return block
  }

 async writeRaw(buf) {
    const { length } = await this.#writerCore.append(buf)
    const index = length - 1
    const coreDiscoveryKey = this.#writerCore.discoveryKey
    if (!coreDiscoveryKey) {
      throw new Error('Writer core is not ready')
    }
    const versionId = getVersionId({ coreDiscoveryKey, index })
    return versionId
  }

```
