### ISSUE TITLE
Delete indexed data when leaving a project

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#427]
## Description

Follow-up item based on discussions around https://github.com/digidem/mapeo-core-next/pull/410. Implementing it requires updating the multi-core and sqlite indexers first, and then updating the `IndexWriter` and `MapeoProject.leave()` to take advantage of the changes.

## Tasks

- [ ] Update [multi-core-indexer](https://github.com/digidem/multi-core-indexer/issues/26)
- [ ] Update [mapeo-sqlite-indexer](https://github.com/digidem/mapeo-sqlite-indexer/issues/22)
- [ ] Add a method to `IndexWriter` to call the relevant method for each sqlite indexer instance
- [ ] Update `MapeoProject.leave()` implementation to use the new methods. Also have to keep in mind that the order in which they're called is important:

  1. Delete core data (already implemented)
  2. Reset multicore indexer state
  3. Delete data from index tables
