### ISSUE TITLE
remove bundled config from repo

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#496]
## Description
For now we're bundling the default config (which actually is based from an incorrect repo) as a zip in the repo
The idea would be to remove the bundled config from the repo, add the mapeo-settings-builder as a devDep, have a build step which basically pulls the mapeo-default-config repo, builds it using mapeo-settings-builder and uses the resulting bundled config for tests.

## Tasks

- [x] remove default config
- [x] add mapeo-default-settings as devDep
- [ ] update tests to reflect the correct config

**Comment by tomasciccola** [comment]
I've been trying different approaches to bundling the config as a build step. 
From what I've seen, config repos have their own build step, which generate the corresponding `mapeosettings` file with everything bundled. But the npm package for a config (I don't know if there exists a npm package for every config, but at least for the default config) doesn't have all the unbundled files: it has a dist folder with all the generated files extracted (so, no tar nor zip archive).

So I think there are different approaches to solving this:
1. The default config knows how to build itself using the config builder. We update a version of the default-config with the zip file in the dist folder. The build step on the mapeo-core-next repo just copies the zip from `node_modules/mapeo-default-config/dist/` over to the config folder
2. The default config doesn't build itself. We update the npm version with the unbundled files. mapeo-core-next has the config-builder and the default-config as dependencies and runs a `build:config` script wich calls the settings-builder with the default-config

There's probably other combinations of this, but I think this two are the most straight away. 
I think it makes sense that configs have the settings-builder as a dependency and `mapeo-core-next` has only the default settings as a devDep, and the build step only constists of copying the generated config to the corresponding folder. 


@gmaclennan @EvanHahn  comments??

**Comment by EvanHahn** [comment]
I don't have a strong opinion, but I think option 1 makes the most sense: let the config builder repo build the ZIP.
