### ISSUE TITLE
Tracking Issue: update default config

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#551]
## Tasks

- [ ] https://github.com/digidem/id-presets-builder/pull/8
- [ ] https://github.com/digidem/mapeo-settings-builder/pull/53
- [ ] https://github.com/digidem/mapeo-default-config/issues/39
- [ ] #496
