### ISSUE TITLE
Serving and recording audio

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#629]
## Tasks

- [ ] How does the frontend records audio and 'send it' to the backend? (Do we have restrictions in i.e. duration?)
- [ ] Se how to serve audio (through a server, like blob? can we stream it instead of serving the whole thing? is there an advantage?)
- [ ] What codec and format are we using?
- [ ] Do we use an external library for decoding or native OS features?
- [ ] Do we generate low bitrate previews?

**Comment by tomasciccola** [comment]
closing since most of the work was done on BlobApi already
