### ISSUE TITLE
Tracking issue: add colors to field

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#651]
## Tasks

- [x] https://github.com/digidem/mapeo-schema/issues/182
- [x] https://github.com/digidem/id-presets-builder/pull/13
- [x] https://github.com/digidem/mapeo-settings-builder/pull/58
- [x] https://github.com/digidem/mapeo-default-config/pull/56
- [x] https://github.com/digidem/mapeo-mock-data/pull/4
- [x] https://github.com/digidem/mapeo-core-next/pull/655
