### ISSUE TITLE
Tracking issue: add release flows for backend projects

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#671]
The idea is to add CI flows for a series of projects to allow publishing them to npm from github actions. 

List of projects to add flows to:
- [x] https://github.com/digidem/mapeo-default-config/pull/42
- [x] https://github.com/digidem/mapeo-settings-builder/pull/55
- [x] https://github.com/digidem/id-presets-builder/pull/11
- [x] https://github.com/digidem/mapeo-mock-data/pull/6

For now the CI flow is based on [@mapeo/schema](https://github.com/digidem/mapeo-schema/blob/main/.github/workflows/release.yml)

**Comment by tomasciccola** [comment]
closing since all the tasks are completed
