### ISSUE TITLE
Tracking issue: Update config file to expose additional metadata

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-core-next#727]
This additional metadata is basically:
`buildDate` -> date when the config was built
`name` -> name of the config
`configFileVersion` -> version of the config file format

- [x] https://github.com/digidem/mapeo-schema/pull/197
- [x] https://github.com/digidem/mapeo-schema/pull/203
- [x] https://github.com/digidem/mapeo-mock-data/pull/8
- [x] https://github.com/digidem/mapeo-settings-builder/pull/65
- [x] https://github.com/digidem/mapeo-default-config/pull/60
- [x] https://github.com/digidem/mapeo-core-next/pull/741
- [x] https://github.com/digidem/mapeo-core-next/pull/721
