### ISSUE TITLE
Add CRUD methods for each datatype to the project instance API

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#95]
## Description

Exposing a client API for working with Mapeo DataTypes. Essentially a CRUD interface

Related to #74

## Tasks

- [ ] `project[schemaName].create()`
- [ ] `project[schemaName].getByDocId()`
- [ ] `project[schemaName].getByVersionId()`
- [ ] `project[schemaName].getMany()`
- [ ] `project[schemaName].update()`
- [ ] `project[schemaName].delete()`

**Comment by gmaclennan** [comment]
Closing in favour of tracking each data type separately.
